[pytest]
testpaths = tests
python_files = test_*.py
filterwarnings =
    ignore::DeprecationWarning:kafka.*
    ignore::DeprecationWarning:importlib.*
    ignore::starlette.exceptions.StarletteDeprecationWarning
    ignore::DeprecationWarning:starlette.*
